language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before install:
  - npm install -g codecov
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
